name: Background Training

on:
  workflow_dispatch:
    inputs:
      iterations:
        required: true
        default: 2

jobs:
  background-training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script with periodic artifact generation
      run: |
        python main.py < Scripts/training_script.txt >> training.log
        for ((i=1; i<${{ inputs.iterations }}; i++)); do
          echo "Starting iteration $i"
          python main.py -mode Update
        done
        python main.py < Scripts/save_model_script.txt

    - name: Save best model
      uses: actions/upload-artifact@v4
      with:
        name: best-models
        path: Models/default.pkl

    - name: Save report
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: Reports/default_report.jpg
